Fixing StringIndexOutOfBoundsException
I'm not really sure what this code is doing or what ID is supposed to look like. So this is just a minimum-intrusion change to avoid an exception.

java.lang.StringIndexOutOfBoundsException: String index out of range: -1
        at java.lang.String.substring(String.java:1875)
        at hudson.tasks.junit.PackageResult.findCorrespondingResult(PackageResult.java:86)
        at hudson.tasks.junit.TestResult.findCorrespondingResult(TestResult.java:295)
        at hudson.tasks.test.AbstractTestResultAction.findCorrespondingResult(AbstractTestResultAction.java:183)
        at hudson.tasks.test.TestResult.getResultInBuild(TestResult.java:162)
        at hudson.tasks.junit.History.getList(History.java:82)
        at hudson.tasks.junit.History$1.createDataSet(History.java:105)
        at hudson.tasks.junit.History$GraphImpl.createGraph(History.java:169)
        at hudson.util.Graph.render(Graph.java:87)
        at hudson.util.Graph.doPng(Graph.java:98)