Prevent stdio trimming from creating invalid unicode data
CaseResult.possiblyTrimStdio() creates substrings according to UTF-16
(java `char`) boundaries. When stdio contains Unicode supplementary
characters, this method can create unpaired surrogates by splitting a
single unicode character "in half". Such strings can't be converted to
UTF-8 and cause build failures:

FATAL: Failed to save the JUnit test result
java.io.IOException: java.lang.RuntimeException: Failed to serialize hudson.tasks.junit.TestResult#suites for class hudson.tasks.junit.TestResult
Caused by: java.lang.RuntimeException: Failed to serialize hudson.tasks.junit.TestResult#suites for class hudson.tasks.junit.TestResult
Caused by: java.lang.RuntimeException: Failed to serialize hudson.tasks.junit.SuiteResult#stderr for class hudson.tasks.junit.SuiteResult
Caused by: [com.thoughtworks.xstream.io](http://com.thoughtworks.xstream.io/).StreamException: Invalid character 0xd83a in XML stream

Fix trimming to remove unpaired trailing (low) surrogates at the
beginning of truncated strings and unpaired leading (high) surrogates at
the end of truncated strings.